error handling

diff --git a/mkreport b/mkreport
--- a/mkreport
+++ b/mkreport
@@ -30,13 +30,14 @@ if [[ ! $# > $OPTIND ]];then
     exit 1
 fi
 
-inputs="${@:$OPTIND:$#-$OPTIND}"
-output=${@:$#}
+readonly inputs="${@:$OPTIND:$#-$OPTIND}"
+readonly output=${@:$#}
 
 if [[ ! $output =~ \.pdf$ ]];then
     echo "Warning: output is not a pdf"
     read -p "continue? (y/N) " yn
     case $yn in
+        [Yy]*);;
         [Nn]*|*) exit;;
     esac
 fi
@@ -56,29 +57,31 @@ fi
 echo "${inputs[@]} -> $output"
 
 convert_single(){
+    # exit 1
     i=$1
     jpg=$2
     pdf=$3
     if [ $COLOR_TYPE == 'binary' ];then
-        echo "creating intermediate file: $jpg"
-        python3 `dirname ${BASH_SOURCE[0]}`/convert.py -t $COLOR_TYPE -o $OUTPUT_TYPE $i $jpg
-        echo "creating intermediate file: $pdf"
-        convert -page a4 -density 72 $jpg $pdf
-        echo "removing intermediate file: $jpg"
+        echo "[$$] creating intermediate file: $jpg"
+        python3 `dirname ${BASH_SOURCE[0]}`/convert.py -t $COLOR_TYPE -o $OUTPUT_TYPE $i $jpg || exit 1
+        echo "[$$] creating intermediate file: $pdf"
+        convert -page a4 -density 72 $jpg $pdf || exit 1
+        echo "[$$] removing intermediate file: $jpg"
         rm $jpg
     else
-        echo "creating intermediate file: $pdf"
-        convert -page a4 -density 72 $i $pdf
+        echo "[$$] creating intermediate file: $pdf"
+        convert -page a4 -density 72 $i $pdf || exit 1
     fi
 }
 
 pdfs=()
 intermediate=()
+pids=()
 
 for i in $inputs;do
     if [ ! -f $i ];then
         echo "File not found: $i"
-        exit 1
+        continue
     fi
 
     if [[ $i =~ \.pdf$ ]];then
@@ -89,15 +92,29 @@ for i in $inputs;do
         pdf=$name-$RANDOM.pdf
 
         convert_single $i $jpg $pdf &
+        pids+=($!)
         pdfs+=($pdf)
-        intermediate+=($pdf)
+        intermediate+=($pdf $jpg)
     fi
 done
 
-wait
+# wait
+for pid in ${pids[@]};do
+    if ! wait $pid; then
+        error=1
+    fi
+done
 
-echo "creating output file: $output"
-pdftk ${pdfs[@]} cat output $output
-echo "removing intermediate file: ${intermediate[@]}"
-rm ${intermediate[@]}
-echo "done!"
+if [[ ! $error ]];then
+    echo "creating output file: $output"
+    pdftk ${pdfs[@]} cat output $output
+    echo "removing intermediate file: ${intermediate[@]}"
+    rm -f ${intermediate[@]}
+    echo "Done!"
+else
+    echo "Error: failed to create intermediate file"
+    echo "removing intermediate file: ${intermediate[@]}"
+    rm -f ${intermediate[@]}
+    echo "Error"
+    exit 1
+fi
